import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class GuidesService {
  constructor(private prismaService: PrismaService) {}

  async getCountries(): Promise<string[]> {
    const countries = await this.prismaService.countries.findMany({ select: { name: true } });

    return countries.map((country) => country.name);
  }

  async getGenres(): Promise<string[]> {
    const genres = await this.prismaService.genre.findMany({ select: { name: true } });

    return genres.map((genre) => genre.name);
  }

  getLanguageNameByLangCode(langCode: string): string {
    const titleByLang = {
      en: 'English',
      eng: 'English',
      ru: 'Русский',
      rus: 'Русский',
      und: 'Неизвестно',
      ar: 'العربية',
      es: 'Español',
      esp: 'Español',
      fr: 'Français',
      fra: 'Français',
      de: 'Deutsch',
      ger: 'Deutsch',
      it: 'Italiano',
      ita: 'Italiano',
      pt: 'Português',
      por: 'Português',
      ja: '日本語',
      jpn: '日本語',
      ko: '한국어',
      kor: '한국어',
      zh: '中文',
      chi: '中文',
      hi: 'हिन्दी',
      hin: 'हिन्दी',
      tr: 'Türkçe',
      tur: 'Türkçe',
      fa: 'فارسی',
      per: 'فارسی',
      th: 'ไทย',
      tha: 'ไทย',
      vi: 'Tiếng Việt',
      vie: 'Tiếng Việt',
      nl: 'Nederlands',
      dut: 'Nederlands',
      pl: 'Polski',
      pol: 'Polski',
      sv: 'Svenska',
      swe: 'Svenska',
      da: 'Dansk',
      dan: 'Dansk',
      fi: 'Suomi',
      fin: 'Suomi',
      no: 'Norsk',
      nor: 'Norsk',
      cs: 'Čeština',
      ces: 'Čeština',
      cz: 'Čeština',
      hu: 'Magyar',
      hun: 'Magyar',
      el: 'Ελληνικά',
      gre: 'Ελληνικά',
      he: 'עברית',
      heb: 'עברית',
      ro: 'Română',
      rum: 'Română',
      bg: 'Български',
      bul: 'Български',
      uk: 'Українська',
      ukr: 'Українська',
      sr: 'Српски',
      srp: 'Српски',
      hr: 'Hrvatski',
      hrv: 'Hrvatski',
      sl: 'Slovenščina',
      slv: 'Slovenščina',
      sk: 'Slovenčina',
      slo: 'Slovenčina',
      lt: 'Lietuvių',
      lit: 'Lietuvių',
      lv: 'Latviešu',
      lav: 'Latviešu',
      et: 'Eesti',
      est: 'Eesti',
      sq: 'Shqip',
      alb: 'Shqip',
      is: 'Íslenska',
      ice: 'Íslenska',
      ga: 'Gaeilge',
      iri: 'Gaeilge',
      cy: 'Cymraeg',
      wel: 'Cymraeg',
      mt: 'Malti',
      mlt: 'Malti',
      eu: 'Euskara',
      bqs: 'Euskara',
      lb: 'Lëtzebuergesch',
      ltz: 'Lëtzebuergesch',
      mi: 'Māori',
      mao: 'Māori',
      oc: 'Occitan',
      oci: 'Occitan',
      id: 'Bahasa Indonesia',
      ind: 'Bahasa Indonesia',
      ms: 'Bahasa Melayu',
      may: 'Bahasa Melayu',
      tl: 'Filipino',
      fil: 'Filipino',
      sw: 'Kiswahili',
      swa: 'Kiswahili',
      am: 'አማርኛ',
      amh: 'አማርኛ',
      hy: 'Հայերեն',
      arm: 'Հայերեն',
      ka: 'ქართული',
      geo: 'ქართული',
      az: 'Azərbaycanca',
      aze: 'Azərbaycanca',
      uz: 'Oʻzbekcha',
      uzb: 'Oʻzbekcha',
      kk: 'Қазақ тілі',
      kaz: 'Қазақ тілі',
      ky: 'Кыргызча',
      kir: 'Кыргызча',
      tk: 'Türkmençe',
      tuk: 'Türkmençe',
      mn: 'Монгол',
      mon: 'Монгол',
      my: 'မြန်မာဘာသာ',
      bur: 'မြန်မာဘာသာ',
      km: 'ភាសាខ្មែរ',
      khm: 'ភាសាខ្មែរ',
      lo: 'ພາສາລາວ',
      lao: 'ພາສາລາວ',
      ne: 'नेपाली',
      nep: 'नेपाली',
      pa: 'ਪੰਜਾਬੀ',
      pan: 'ਪੰਜਾਬੀ',
      te: 'తెలుగు',
      tel: 'తెలుగు',
      ta: 'தமிழ்',
      tam: 'தமிழ்',
      si: 'සිංහල',
      sin: 'සිංහල',
      ur: 'اردو',
      urd: 'اردو',
      bn: 'বাংলা',
      ben: 'বাংলা',
      gu: 'ગુજરાતી',
      guj: 'ગુજરાતી',
      mr: 'मराठी',
      mar: 'मराठी',
      kn: 'ಕನ್ನಡ',
      kan: 'ಕನ್ನಡ',
      as: 'অসমীয়া',
      asm: 'অসমীয়া',
      or: 'ଓଡ଼ିଆ',
      ori: 'ଓଡ଼ିଆ',
      sa: 'संस्कृतम्',
      san: 'संस्कृतम्',
      sd: 'سنڌي',
      snd: 'سنڌي',
      kok: 'कोंकणी',
      doi: 'डोगरी',
      mni: 'ꯃꯤꯇꯩ ꯂꯣꯟ',
      sit: 'ᱥᱟᱱᱛᱟᱲᱤ',
    };

    return titleByLang[langCode.toLowerCase()] || 'Неизвестно';
  }
}
