version: '3.8'

services:

  postgres_db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres_prod:
    image: postgres:14-alpine
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_admin
      POSTGRES_DB: prod_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  postgres:
  pgdata_prod: