-- AlterTable
ALTER TABLE "Series" ALTER COLUMN "rate_imdb" SET DEFAULT 9.0,
ALTER COLUMN "rate_imdb" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rate_kinopoisk" SET DEFAULT 9.0,
ALTER COLUMN "rate_kinopoisk" SET DATA TYPE DOUBLE PRECISION;
